apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: krazytogo-data
  namespace: krazytogo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: # set to your cluster default or preferred class
