apiVersion: v1
kind: Service
metadata:
  name: krazytogo
  namespace: krazytogo
  labels:
    app: krazytogo
spec:
  selector:
    app: krazytogo
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  type: ClusterIP
